[features]
seeds = false
skip-lint = false
[programs.devnet]
myepicproject = "4KBEsT8mw5vnsSPASp2tfFBSya9ymY2NsDPdYa2SfdJD"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/richiehydra/.config/solana/id.json"
[scripts]
test = "node tests/myepicproject.js"

